name: Generate Datas
on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Generate the snake SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: the-youngdev
          outputs: dist/github-contribution-grid-snake.svg

      # Step 2: Push the generated SVG to the 'output' branch
      - name: Push Snake SVG to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
